# Buildpacks to include in builder
[[buildpacks]]
id = "samples/java-maven"
version = "0.0.1"
uri = "../../buildpacks/java-maven"

# Order used for detection
[[order]]
[[order.group]]
id = "samples/java-maven"
version = "0.0.1"

# Base images used to create the builder
[build]
image = "cnbs/sample-base-build:nanoserver-2022"
[run]
[[run.images]]
image = "cnbs/sample-base-run:nanoserver-2022"

# Stack (deprecated) used to create the builder
[stack]
id = "io.buildpacks.samples.stacks.java-maven-nanoserver-2022"
build-image = "cnbs/sample-base-build:nanoserver-2022"
run-image = "cnbs/sample-base-run:nanoserver-2022"
